import 'package:flutter/cupertino.dart';
import '../theme/colors.dart';

class PrivacyPolicyScreen extends StatelessWidget {
  const PrivacyPolicyScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return CupertinoPageScaffold(
      backgroundColor: AppColors.darkBackground,
      navigationBar: CupertinoNavigationBar(
        backgroundColor: AppColors.darkBackground,
        border: null,
        leading: CupertinoButton(
          padding: EdgeInsets.zero,
          onPressed: () => Navigator.of(context).pop(),
          child: const Icon(
            CupertinoIcons.back,
            color: CupertinoColors.white,
          ),
        ),
        middle: const Text(
          'Privacy Policy',
          style: TextStyle(color: CupertinoColors.white),
        ),
      ),
      child: SafeArea(
        child: ListView(
          padding: const EdgeInsets.all(24),
          children: const [
            SizedBox(height: 20),
            _SectionTitle(text: 'Privacy Policy'),
            SizedBox(height: 12),
            _Paragraph(
              text: 'Developer ("us", "we", or "our") operates the Ice Studio mobile application (hereinafter referred to as the "Service"). This page informs you of our policies regarding the collection, use, and disclosure of personal data when you use our Service and the choices you have associated with that data. We use your data to provide and improve the Service. By using the Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, the terms used in this Privacy Policy have the same meanings as in our Terms and Conditions.',
            ),
            SizedBox(height: 24),
            _SectionTitle(text: 'Definitions'),
            SizedBox(height: 12),
            _DefinitionItem(
              term: 'Service',
              definition: 'Service is the Ice Studio mobile application operated by Developer',
            ),
            _DefinitionItem(
              term: 'Personal Data',
              definition: 'Personal Data means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).',
            ),
            _DefinitionItem(
              term: 'Usage Data',
              definition: 'Usage Data is data collected automatically either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).',
            ),
            _DefinitionItem(
              term: 'Cookies',
              definition: 'Cookies are small files stored on your device (computer or mobile device).',
            ),
            SizedBox(height: 24),
            _SectionTitle(text: 'Information Collection and Use'),
            SizedBox(height: 12),
            _Paragraph(
              text: 'We collect several different types of information for various purposes to provide and improve our Service to you.',
            ),
            SizedBox(height: 16),
            _SubsectionTitle(text: 'Types of Data Collected'),
            SizedBox(height: 12),
            _SubsectionTitle(text: 'Personal Data'),
            SizedBox(height: 8),
            _Paragraph(
              text: 'While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you ("Personal Data"). Personally identifiable information may include, but is not limited to: Cookies and Usage Data',
            ),
            SizedBox(height: 16),
            _SubsectionTitle(text: 'Usage Data'),
            SizedBox(height: 8),
            _Paragraph(
              text: 'When you access the Service by or through a mobile device, we may collect certain information automatically, including, but not limited to, the type of mobile device you use, your mobile device unique ID, the IP address of your mobile device, your mobile operating system, the type of mobile Internet browser you use, unique device identifiers and other diagnostic data ("Usage Data").',
            ),
            SizedBox(height: 16),
            _SubsectionTitle(text: 'Tracking & Cookies Data'),
            SizedBox(height: 8),
            _Paragraph(
              text: 'We use cookies and similar tracking technologies to track the activity on our Service and we hold certain information. Cookies are files with a small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Other tracking technologies are also used such as beacons, tags and scripts to collect and track information and to improve and analyse our Service.',
            ),
            SizedBox(height: 8),
            _Paragraph(
              text: 'You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service.',
            ),
            SizedBox(height: 12),
            _Paragraph(text: 'Examples of Cookies we use:', fontWeight: FontWeight.w500),
            _BulletPoint(text: 'Session Cookies. We use Session Cookies to operate our Service.'),
            _BulletPoint(text: 'Preference Cookies. We use Preference Cookies to remember your preferences and various settings.'),
            _BulletPoint(text: 'Security Cookies. We use Security Cookies for security purposes.'),
            SizedBox(height: 24),
            _SectionTitle(text: 'Use of Data'),
            SizedBox(height: 12),
            _Paragraph(text: 'Service uses the collected data for various purposes:'),
            _BulletPoint(text: 'To provide and maintain the Service'),
            _BulletPoint(text: 'To notify you about changes to our Service'),
            _BulletPoint(text: 'To allow you to participate in interactive features of our Service when you choose to do so'),
            _BulletPoint(text: 'To provide customer care and support'),
            _BulletPoint(text: 'To provide analysis or valuable information so that we can improve the Service'),
            _BulletPoint(text: 'To monitor the usage of the Service'),
            _BulletPoint(text: 'To detect, prevent and address technical issues'),
            SizedBox(height: 24),
            _SectionTitle(text: 'Transfer Of Data'),
            SizedBox(height: 12),
            _Paragraph(
              text: 'Your information, including Personal Data, may be transferred to - and maintained on - computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from your jurisdiction.',
            ),
            SizedBox(height: 8),
            _Paragraph(
              text: 'If you are located outside Seychelles and choose to provide information to us, please note that we transfer the data, including Personal Data, to Seychelles and process it there.',
            ),
            SizedBox(height: 8),
            _Paragraph(
              text: 'Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.',
            ),
            SizedBox(height: 8),
            _Paragraph(
              text: 'Service will take all steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of your data and other personal information.',
            ),
            SizedBox(height: 24),
            _SectionTitle(text: 'Disclosure Of Data'),
            SizedBox(height: 12),
            _SubsectionTitle(text: 'Legal Requirements'),
            SizedBox(height: 8),
            _Paragraph(text: 'Service may disclose your Personal Data in the good faith belief that such action is necessary to:'),
            _BulletPoint(text: 'To comply with a legal obligation'),
            _BulletPoint(text: 'To protect and defend the rights or property of Service'),
            _BulletPoint(text: 'To prevent or investigate possible wrongdoing in connection with the Service'),
            _BulletPoint(text: 'To protect the personal safety of users of the Service or the public'),
            _BulletPoint(text: 'To protect against legal liability'),
            SizedBox(height: 8),
            _Paragraph(
              text: 'As an European citizen, under GDPR, you have certain individual rights. You can learn more about these guides in the GDPR Guide.',
            ),
            SizedBox(height: 24),
            _SectionTitle(text: 'Security of Data'),
            SizedBox(height: 12),
            _Paragraph(
              text: 'The security of your data is important to us but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.',
            ),
            SizedBox(height: 24),
            _SectionTitle(text: 'Service Providers'),
            SizedBox(height: 12),
            _Paragraph(
              text: 'We may employ third party companies and individuals to facilitate our Service ("Service Providers"), to provide the Service on our behalf, to perform Service-related services or to assist us in analyzing how our Service is used.',
            ),
            SizedBox(height: 8),
            _Paragraph(
              text: 'These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.',
            ),
            SizedBox(height: 24),
            _SectionTitle(text: 'Links to Other Sites'),
            SizedBox(height: 12),
            _Paragraph(
              text: 'Our Service may contain links to other sites that are not operated by us. If you click a third party link, you will be directed to that third party\'s site. We strongly advise you to review the Privacy Policy of every site you visit.',
            ),
            SizedBox(height: 8),
            _Paragraph(
              text: 'We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.',
            ),
            SizedBox(height: 24),
            _SectionTitle(text: 'Children\'s Privacy'),
            SizedBox(height: 12),
            _Paragraph(
              text: 'Our Service does not address anyone under the age of 18 ("Children"). We do not knowingly collect personally identifiable information from anyone under the age of 18. If you are a parent or guardian and you are aware that your Child has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from children without verification of parental consent, we take steps to remove that information from our servers.',
            ),
            SizedBox(height: 24),
            _SectionTitle(text: 'Changes to This Privacy Policy'),
            SizedBox(height: 12),
            _Paragraph(
              text: 'We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.',
            ),
            SizedBox(height: 8),
            _Paragraph(
              text: 'We will let you know via email and/or a prominent notice on our Service, prior to the change becoming effective and update the "effective date" at the top of this Privacy Policy.',
            ),
            SizedBox(height: 8),
            _Paragraph(
              text: 'You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.',
            ),
            SizedBox(height: 48),
          ],
        ),
      ),
    );
  }
}

class _SectionTitle extends StatelessWidget {
  final String text;

  const _SectionTitle({required this.text});

  @override
  Widget build(BuildContext context) {
    return Text(
      text,
      style: const TextStyle(
        fontSize: 22,
        fontWeight: FontWeight.w600,
        color: CupertinoColors.white,
      ),
    );
  }
}

class _SubsectionTitle extends StatelessWidget {
  final String text;

  const _SubsectionTitle({required this.text});

  @override
  Widget build(BuildContext context) {
    return Text(
      text,
      style: const TextStyle(
        fontSize: 18,
        fontWeight: FontWeight.w600,
        color: CupertinoColors.white,
      ),
    );
  }
}

class _Paragraph extends StatelessWidget {
  final String text;
  final FontWeight? fontWeight;

  const _Paragraph({required this.text, this.fontWeight});

  @override
  Widget build(BuildContext context) {
    return Text(
      text,
      style: TextStyle(
        fontSize: 15,
        height: 1.5,
        fontWeight: fontWeight,
        color: CupertinoColors.white.withOpacity(0.85),
      ),
    );
  }
}

class _DefinitionItem extends StatelessWidget {
  final String term;
  final String definition;

  const _DefinitionItem({required this.term, required this.definition});

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 12),
      child: RichText(
        text: TextSpan(
          style: TextStyle(
            fontSize: 15,
            height: 1.5,
            color: CupertinoColors.white.withOpacity(0.85),
          ),
          children: [
            TextSpan(
              text: '$term: ',
              style: const TextStyle(
                fontWeight: FontWeight.w600,
                color: CupertinoColors.white,
              ),
            ),
            TextSpan(text: definition),
          ],
        ),
      ),
    );
  }
}

class _BulletPoint extends StatelessWidget {
  final String text;

  const _BulletPoint({required this.text});

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.only(left: 16, bottom: 8),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          const Padding(
            padding: EdgeInsets.only(top: 8, right: 8),
            child: Icon(
              CupertinoIcons.circle_fill,
              size: 6,
              color: CupertinoColors.systemGrey,
            ),
          ),
          Expanded(
            child: Text(
              text,
              style: TextStyle(
                fontSize: 15,
                height: 1.5,
                color: CupertinoColors.white.withOpacity(0.85),
              ),
            ),
          ),
        ],
      ),
    );
  }
}
